version: "3"

services:
  game:
    build: .
    image: southclaws/scavenge-survive:latest
    environment:
      AUTO_BUILD: "1" # auto build on source code changes
      NO_BUILD_INCREMENT: "1" # don't increment BUILD_NUMBER
    volumes:
      - ./:/server/
    ports:
      - 0.0.0.0:7777:7777/udp
