version: "3"

services:
  game:
    build: .
    image: southclaws/scavenge-survive:latest
    command: package run
    environment:
      AUTO_BUILD: "1" # auto build on source code changes
    volumes:
      - ./:/server/
    ports:
      - 7777:7777/udp
